### ISSUE TITLE
Weird thing with your account

### ISSUE THREAD

**Issue by Alex-Blade** [sauerbraten/pkb#1]
Hey, I've actually have no idea who are you, but commits from my home pc are registering on you somehow... Have you encountered such problem before?
![image](https://user-images.githubusercontent.com/44120047/96890896-c94c5080-1490-11eb-94ad-4a58642e0fcc.png)

**Comment by sauerbraten** [comment]
I guess that's because I had alex@localhost.localdomain as one of my emails in my account. I removed it from my account, but chances are that you will experience this issue again unless you set up an email in your local Git configuration: https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by Alex-Blade** [comment]
Ah, I see, I've already started to worry ab ssh keys
